services:
#    colocation.example:
#        class: ColocationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
     colocation.reservation_purger:
         class: ColocationBundle\Purger\ReservationPurger
         arguments: ["@doctrine.orm.entity_manager"]
