evenement_e:
    resource: "@EvenementBundle/Resources/config/routing/evenement.yml"
    prefix:   /e

evenement_homepage:
    path:     /home
    defaults: { _controller: EvenementBundle:Default:index }

club:
    resource: "@EvenementBundle/Resources/config/routing/club.yml"
    prefix:   /club


