<?php

namespace EvenementBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
    function recherche($r){
        return $this->createQueryBuilder('e')
            ->where('e.description Like :v')
            ->orWhere('e.nom Like :v')
            ->orWhere('e.lieu Like :v')
            ->setParameter('v','%'.$r.'%')
            ->getQuery()
            ->getResult();
    }
}
