<?php

namespace EvenementBundle\Repository;

/**
 * PartClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartClubRepository extends \Doctrine\ORM\EntityRepository
{
}
