<?php

namespace GestionCovoiturageBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * ReservationCovoiturageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ReservationcovoiturageRepository extends EntityRepository
{

    public function findAnnoncesRes($id)
    {
        $query= $this->getEntityManager()->createQuery("SELECT v FROM GestionCovoiturageBundle:Reservationcovoiturage v WHERE  v.IdReserve =:id")
            ->setParameter('IdReserve',$id);
        return $query->getResult();
    }

    public function findAnnoncesEtat($etat){

        $query= $this->getEntityManager()->createQuery("SELECT v FROM GestionCovoiturageBundle:Reservationcovoiturage v WHERE  v.etat =:etat")
            ->setParameter('etat', $etat);
        return $query->getResult();

    }

    public function existe($col,$user)
    {

        $query= $this->getEntityManager()->createQuery("SELECT v FROM GestionCovoiturageBundle:Reservationcovoiturage v WHERE  v.idAnnonce =:col AND v.idReserve =:user")
            ->setParameter('idAnnonce', $col)
            ->setParameter('idReserve',$user) ;
        return $query->getResult();
    }


}
