<?php

namespace RevisionBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAjax($search)
    {

        return $this->createQueryBuilder('c')
            ->andWhere('c.module LIKE :module')
            ->setParameter('module','%' .$search . '%')
            ->getQuery()
            ->getResult();
    }

}
