<?php

namespace RevisionBundle\Repository;

/**
 * ReservationSalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationSalleRepository extends \Doctrine\ORM\EntityRepository
{
}
