services:
#    reclamation.example:
#        class: ReclamationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
     reclamation.reservation_purger:
         class: ReclamationBundle\Purge\PurgeReclamation
         arguments: ["@doctrine.orm.entity_manager"]

